### ISSUE TITLE
Foundry 8.9 causes layout issues.

### ISSUE THREAD

**Issue by Mejari** [illandril/FoundryVTT-chat-enhancements#12]
Looks like something about the latest upgrade to 8.9 does some layout changes. The current speaker display element fills up available vertical space.

After experimenting it looks like a new `flexcol` class is taking priority. Changing the `.illandril-chat-enhancements--currentSpeaker` css flex declaration to be `!important` fixes the issue:

    .illandril-chat-enhancements--currentSpeaker {
      flex: 0 !important;
      padding: 3px 0.5em;
    }

Alternatively providing a more specific declaration including the new `flexcol` class works as well:

    .flexcol > .illandril-chat-enhancements--currentSpeaker {
      flex: 0;
      padding: 3px 0.5em;
    }

**Comment by Artetsu** [comment]
Is there an ETA on when this might be fixed? I don't know how to fix this on my own.

**Comment by illandril** [comment]
I should have time to get a new release out with a fix by the end of this weekend.

**Comment by Mejari** [comment]
@Artetsu in the meantime you can manually edit the CSS declaration as mentioned in the issue. You can open it in a normal text editor, should be the first text in the file. It'll be the `styles.css` file in the `modules\illandril-chat-enhancements` in your Foundry install folder.

**Comment by illandril** [comment]
I managed to free up a few spare minutes before bed - it should be fixed tonight.
