### ISSUE TITLE
Setting to Disable Parts of the Module

### ISSUE THREAD

**Issue by MrVauxs** [illandril/FoundryVTT-chat-enhancements#14]
**Is your feature request related to a problem? Please describe.**
I have a problem of duplicate information. I very much like the ability to see who I am talking as, but there's at least three different modules that allow for seeing who is the speaker of a message. It would be great to be able to disable the player name suffix next to the character name.

Given that this is almost 1/3-1/4th of the module, you could do such settings for the rest of the module as well.

**Describe the solution you'd like**
A simple on/off setting disabling the particular function.

**Describe alternatives you've considered**
None. It's rather simple.

**What system(s) do you want this feature to work with?**
This is mainly considering Pathfinder 2e's PF2e Dorako UI module.

**What other modules do you use that you want to ensure work well with this feature?**
See above.

**Additional context**
![image](https://user-images.githubusercontent.com/32039708/187041131-0b5331d3-0bd4-4e29-9bec-a7e2edebe251.png)

**Comment by MrVauxs** [comment]
For reference I went ahead and simply made a module of my own, [Speaking As](https://github.com/MrVauxs/speaking-as), to remedy the lack of this feature.

**Comment by illandril** [comment]
I made a mention of your module on this module's main GitHub page so others who might want the same thing will know about it and have that as an option until I'm able to free up time to add some settings.
