### ISSUE TITLE
Archived Chats not opening - JSON error. Rogue characters?

### ISSUE THREAD

**Issue by Lukasrygh23** [illandril/FoundryVTT-chat-enhancements#16]
**Describe the bug**
Hi! This module is really useful, but the chat archive feature doesn't seem to work for me. 

**What steps did you take before experiencing the problem?**
1. Click on "Archive Chat log" in the chat window
2. Create a chatlog (any amount of chat selected)
3. Go to "Manage Chat Archives" in settings
4. Click any archive in there, including the one just created.

**What did you expect to happen?**
A chatlog to appear that I could access through Foundry.

**What happened instead?**
I recieved an "Unexpected character" error and several other errors, all reproduced below. 

**Screenshots**
[The Error I got when attempting to open the chatlog originally.](https://media.discordapp.net/attachments/722566083499786352/1036315983155044392/unknown.png)
[The current error.](https://media.discordapp.net/attachments/201036751773499393/1037176794060693514/unknown.png)
[Error with all modules except DF chat disabled.](https://media.discordapp.net/attachments/201036751773499393/1037178056332283925/unknown.png)
[Unsure if this is related but dumping it anyway.](https://media.discordapp.net/attachments/201036751773499393/1037180060995702936/unknown.png)

**Foundry Versions**
 - Version of this module: 4.1.0
 - Foundry Version: V10 Build 287
 - System Name and Version: Oracle Cloud host, accessed via windows 10. 
 - Browser Name and Version: Firefox and Chrome both tested.

**What other modules did you have active when experiencing this issue (include both names and versions)?**
 [Full list of active modules as of most recent test. ](https://media.discordapp.net/attachments/201036751773499393/1037177400527695955/unknown.png)
[Without all modules I get a slightly different error.](https://media.discordapp.net/attachments/201036751773499393/1037178056332283925/unknown.png)

**Additional context**
 I've tested this on a fresh foundry install and it seems to function, so I'm not quite sure what's causing the incompatability or if it's something in my old chat archives. 
[Full list of active modules as of most recent test. ](https://media.discordapp.net/attachments/201036751773499393/1037177400527695955/unknown.png)

I used ViNo in V9 but have since disabled and uninstalled it. 

I've tested by posting several messages in the recent chat and ONLY archiving those, and it seems to display fine. I can provide the JSON archives creating the errors but would rather not upload publicly, as they contain NSFW content and I don't quite know what github's policy is.

**Comment by illandril** [comment]
This is the GitHub page for Illandril's Chat Enhancements, which has nothing to do with chat archiving.
You'll have to report your issue to the DF Chat Enhancements' author.

**Comment by Lukasrygh23** [comment]
I'm an idiot, sorry. I meant to go to a different github page.
