### ISSUE TITLE
FoundryVTT Package Manager Manifest Link is Incorrect

### ISSUE THREAD

**Issue by Soyvolon** [illandril/FoundryVTT-chat-enhancements#217]
**Describe the bug**
The manifest link for the four most recent versions of the module on foundry is set to the `latest` url - meaning that no matter what manifest version you try to download, it will always direct you to the latest (throwing errors on older versions of foundry).

see: https://foundryvtt.com/packages/illandril-chat-enhancements/

Versions 3.0.0 to 2.1.5 all have the same manifest link: `https://github.com/illandril/FoundryVTT-chat-enhancements/releases/latest/download/module.json`

**What did you expect to happen?**
Manifest links should point to version-specific release tags, not the latest tag.

**Comment by illandril** [comment]
Until the FoundryVTT fixes the nuisance that is the "different installation URL" warning, this will not be fixed.

See reasoning here: https://github.com/illandril/FoundryVTT-token-tooltips/issues/102#issuecomment-2146125196
